spring:
  application:
    name: "demo-01"
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        enable.idempotence: true
        schema.registry.url: http://localhost:8081
    consumer:
      bootstrap-servers: localhost:9092
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest   #earliest|latest|none
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        schema.registry.url: http://localhost:8081
